name: Pipeline CI 

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Configurar Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Passando o Flake8
        run: |
           flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      
      - name: Passando o MyPy para erros de tipo
        run: |
          mypy --install-types
          mypy app

      - name: Rodar Testes com Pytest
        run: |
          pytest